version: "3.9"

services:

  bitcoind-snapshot-init:
    profiles: ["snapshot-init"]
    build:
      context: .
      dockerfile: Dockerfile.btc
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./init-data:/init-data
      - bitcoind:/bitcoin-data
    ports:
      - "18443:18443"
      - "18444:18444"
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        rm -rf /bitcoin-data/*
        bitcoind &
        btcd=$$!
        bitcoin-cli -rpcwait getmininginfo
        bitcoin-cli importaddress $BTC_ADDR "" false
        bitcoin-cli generatetoaddress $INIT_BLOCKS $BTC_ADDR
        bitcoin-cli stop
        wait $$btcd
        tar -C /bitcoin-data -czf /init-data/bitcoind.tar.gz ./


  bitcoind:
    profiles: ["default", "bitcoind-only"]
    build:
      context: .
      dockerfile: Dockerfile.btc
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./init-data:/init-data
      - bitcoind:/bitcoin-data
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        rm -rf /bitcoin-data/*
        tar -xf /init-data/bitcoind.tar.gz -C /bitcoin-data
        # bitcoind -conf=/root/.bitcoin/bitcoin.conf -datadir=/bitcoin-data
        bitcoind
    healthcheck:
      test: bitcoin-cli -rpcwait getmininginfo
      interval: 100ms
      timeout: 30s

  bitcoind-miner:
    profiles: ["default"]
    build:
      context: .
      dockerfile: Dockerfile.btc
    volumes:
      - ./bitcoind-miner.sh:/usr/bin/bitcoind-miner.sh
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - bitcoind:/bitcoin-data
    depends_on:
      bitcoind:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        bitcoin-cli -rpcconnect=bitcoind generatetoaddress 1 $BTC_ADDR
        while true; do
          echo "Checking for Stacks mining tx..."
          tx=$$(bitcoin-cli -rpcconnect=bitcoind listtransactions '*' 1 0 true)
          case "$$tx" in
          *send*)
            echo "Detected Stacks mining tx, starting Bitcoin block auto-mining on $MINE_INTERVAL interval..."
            break
            ;;
          *)
            echo "No Stacks mining tx detected in:"
            echo "$$tx"
            ;;
          esac
          sleep 1s
        done

volumes:
  pgdata:
  bitcoind:
  stacks-data:
