version: "3.9"

services:

  bitcoind-snapshot-init:
    profiles: ["snapshot-init"]
    build:
      context: .
      dockerfile: Dockerfile.btc
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./init-data:/init-data
      - bitcoind:/bitcoin-data
    hostname: bitcoind
    ports:
      - "18443:18443"
      - "18444:18444"
    healthcheck:
      test: bitcoin-cli -rpcwait getmininginfo
      interval: 100ms
      timeout: 30s
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        rm -rf /bitcoin-data/*
        bitcoind &
        btcd=$$!
        bitcoin-cli -rpcwait getmininginfo
        bitcoin-cli importaddress $BTC_ADDR "" false
        bitcoin-cli generatetoaddress $INIT_BLOCKS $BTC_ADDR
        wait $$btcd

  stacks-node-snapshot-init:
    profiles: ["snapshot-init"]
    build:
      context: .
      dockerfile: Dockerfile.stacks-node
      args:
        GIT_COMMIT: 0efa50283bb7cd77f10a9ad8066f9e782a1de067
    hostname: stacks-node
    ports:
      - "20443:20443"
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./stacks-krypton-miner.toml/:/root/config.toml.in
      - ./init-data:/init-data
      - stacks-data:/stacks-blockchain-data
      - bitcoind:/bitcoin-data
    depends_on:
      bitcoind-snapshot-init:
        condition: service_healthy
    environment:
      # STACKS_LOG_TRACE: 1 # uncomment for trace logging
      # STACKS_LOG_DEBUG: 1
      DATA_DIR: /stacks-blockchain-data
      # STACKS_EVENT_OBSERVER: stacks-api:3700
      BITCOIN_PEER_HOST: bitcoind
      BITCOIN_PEER_PORT: 18444
      BITCOIN_RPC_PORT: 18443
      BITCOIN_RPC_USER: krypton
      BITCOIN_RPC_PASS: krypton
      EPOCH_10_START: 0
      EPOCH_20_START: 1
      EPOCH_205_START: 2
      EPOCH_21_START: 3
      POX_2_ACTIVATION: 4
      MINER_SEED: 9e446f6b0c6a96cf2190e54bcd5a8569c3e386f091605499464389b8d4e0bfc201 # stx: STEW4ZNT093ZHK4NEQKX8QJGM2Y7WWJ2FQQS5C19, btc: miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT, pub_key: 035379aa40c02890d253cfa577964116eb5295570ae9f7287cbae5f2585f5b2c7c
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        rm -rf /stacks-blockchain-data/*
        envsubst < config.toml.in > config.toml
        stacks-node start --config=config.toml &
        STACKS_PID=$$!
        while true; do
          HEIGHT=$$(curl localhost:20443/v2/info | jq '.burn_block_height')
          if [ "$$HEIGHT" -ge 101 ]; then
            echo "Stacks node caught up to block 101"
            break
          else
            echo "Stacks node not ready, at block: $$HEIGHT"
          fi
          sleep 0.5s
        done
        kill $$STACKS_PID
        wait $$STACKS_PID
        bitcoin-cli -rpcconnect=bitcoind stop
    healthcheck:
      test: curl --fail-with-body "http://localhost:20443/v2/info" || exit 1
      timeout: 60s
      interval: 300ms
      retries: 1000000

  stacks-node-boostrapped-watcher:
    profiles: ["snapshot-init"]
    build:
      context: .
      dockerfile: Dockerfile.btc
    depends_on:
      bitcoind-snapshot-init:
        condition: service_completed_successfully
      stacks-node-snapshot-init:
        condition: service_completed_successfully
    volumes:
      - ./init-data:/init-data
      - stacks-data:/stacks-blockchain-data
      - bitcoind:/bitcoin-data
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        tar -C /bitcoin-data -czf /init-data/bitcoind.tar.gz ./
        tar -C /stacks-blockchain-data -czf /init-data/stacks-blockchain-data.tar.gz ./

  bitcoind:
    profiles: ["default", "bitcoind-only"]
    build:
      context: .
      dockerfile: Dockerfile.btc
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./init-data:/init-data
      - bitcoind:/bitcoin-data
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        rm -rf /bitcoin-data/*
        tar -xf /init-data/bitcoind.tar.gz -C /bitcoin-data
        bitcoind
    healthcheck:
      test: bitcoin-cli -rpcwait getmininginfo
      interval: 100ms
      timeout: 30s

  bitcoind-miner:
    profiles: ["default"]
    build:
      context: .
      dockerfile: Dockerfile.btc
    volumes:
      - ./bitcoind-miner.sh:/usr/bin/bitcoind-miner.sh
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - bitcoind:/bitcoin-data
    depends_on:
      bitcoind:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        bitcoin-cli -rpcconnect=bitcoind generatetoaddress 1 $BTC_ADDR
        while true; do
          echo "Checking for Stacks mining tx..."
          TX=$$(bitcoin-cli -rpcconnect=bitcoind listtransactions '*' 1 0 true)
          CONFS=$$(echo "$$TX" | jq '.[].confirmations')
          if [ "$$CONFS" = "0" ]; then
            echo "Detected Stacks mining mempool tx:"
            echo "$$TX"
            echo "Mining btc block..."
            bitcoin-cli -rpcconnect=bitcoind generatetoaddress 1 "$BTC_ADDR"
          else
            echo "No Stacks mining tx detected in:"
            echo "$$TX"
          fi
          sleep 0.5s
        done

  stacks-node:
    profiles: ["default"]
    build:
      context: .
      dockerfile: Dockerfile.stacks-node
      args:
        GIT_COMMIT: 0efa50283bb7cd77f10a9ad8066f9e782a1de067
    ports:
      - "20443:20443"
    volumes:
      - ./stacks-krypton-miner.toml/:/root/config.toml.in
      - ./init-data:/init-data
      - stacks-data:/stacks-blockchain-data
    depends_on:
      bitcoind-miner:
        condition: service_started
    environment:
      # STACKS_LOG_TRACE: 1 # uncomment for trace logging
      # STACKS_LOG_DEBUG: 1
      DATA_DIR: /stacks-blockchain-data
      # STACKS_EVENT_OBSERVER: stacks-api:3700
      BITCOIN_PEER_HOST: bitcoind
      BITCOIN_PEER_PORT: 18444
      BITCOIN_RPC_PORT: 18443
      BITCOIN_RPC_USER: krypton
      BITCOIN_RPC_PASS: krypton
      EPOCH_10_START: 0
      EPOCH_20_START: 1
      EPOCH_205_START: 2
      EPOCH_21_START: 3
      POX_2_ACTIVATION: 4
      MINER_SEED: 9e446f6b0c6a96cf2190e54bcd5a8569c3e386f091605499464389b8d4e0bfc201 # stx: STEW4ZNT093ZHK4NEQKX8QJGM2Y7WWJ2FQQS5C19, btc: miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT, pub_key: 035379aa40c02890d253cfa577964116eb5295570ae9f7287cbae5f2585f5b2c7c
    # healthcheck:
    #   test: curl --fail-with-body "http://localhost:20443/v2/info" || exit 1
    #   timeout: 60s
    #   interval: 300ms
    #   retries: 1000000
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        rm -rf /stacks-blockchain-data/*
        tar -xf /init-data/stacks-blockchain-data.tar.gz -C /stacks-blockchain-data
        envsubst < config.toml.in > config.toml
        exec stacks-node start --config=config.toml

volumes:
  pgdata:
  bitcoind:
  stacks-data:
