[node]
name = "krypton-node"
rpc_bind = "0.0.0.0:$RPC_BIND_PORT"
p2p_bind = "0.0.0.0:$P2P_BIND_PORT"
# data_url = "http://127.0.0.1:$RPC_BIND_PORT"
# p2p_address = "127.0.0.1:$RPC_BIND_PORT"
bootstrap_node = "$MINER_BOOTSTRAP"
working_dir = "$DATA_DIR"

seed = "$MINER_SEED"
local_peer_seed = "$MINER_SEED"

miner = true
use_test_genesis_chainstate = true
pox_sync_sample_secs = 10
wait_time_for_blocks = 0
wait_time_for_microblocks = 0
mine_microblocks = false
microblock_frequency = 1000
require_affirmed_anchor_blocks = false

[miner]
min_tx_fee = 1
first_attempt_time_ms = 5
subsequent_attempt_time_ms = 30_000
wait_for_block_download = false
microblock_attempt_time_ms = 10
mining_key = "$MINER_SEED"
$REWARD_RECIPIENT_CONF

[connection_options]
# inv_sync_interval = 10
# download_interval = 10
# walk_interval = 10
# disable_block_download = true
# disable_inbound_handshakes = true
# disable_inbound_walks = true
# public_ip_address = "1.1.1.1:1234"
auth_token = "12345"
# private_neighbors = false

[burnchain]
chain = "bitcoin"
mode = "nakamoto-neon"
poll_time_secs = 1
magic_bytes = "T3"
pox_prepare_length = $POX_PREPARE_LENGTH
pox_reward_length = $POX_REWARD_LENGTH
burn_fee_cap = 20_000

### bitcoind-regtest connection info
peer_host = "$BITCOIN_PEER_HOST"
peer_port = $BITCOIN_PEER_PORT
rpc_port = $BITCOIN_RPC_PORT
rpc_ssl = false
username = "$BITCOIN_RPC_USER"
password = "$BITCOIN_RPC_PASS"
timeout = 30
wallet_name = "main"

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.0"
start_height = $STACKS_20_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = $STACKS_2_05_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = $STACKS_21_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.2"
start_height = $STACKS_22_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.3"
start_height = $STACKS_23_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.4"
start_height = $STACKS_24_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.5"
start_height = $STACKS_25_HEIGHT

[[burnchain.epochs]]
epoch_name = "3.0"
start_height = $STACKS_30_HEIGHT
